### ISSUE TITLE
Multiple Webhooks

### ISSUE THREAD

**Issue by RedQuiet** [Lincoln-LM/sv-live-map#49]
Discord doesn't let any one webhook post to multiple channels in the same server. So if I want more than one channel to get an update, I need multiple webhooks. Support for more than one would be nice so I could sort raids into specific channels. 

Oh and maybe a little drop down to switch between them as well so, for example, if I was to switch to Violet I could use a drop down menu to switch to the Violet webhook instead of my Scarlet one.

**Comment by lincoln-lm** [comment]
possibly a checked combobox (the drop-down used for filters) for selecting different webhooks?

**Comment by lincoln-lm** [comment]
when implemented, an option for an individual "webhook setting" should include whether or not to ping on exception. #53

**Comment by architdate** [comment]
RC is doing this by comma separating it, could probably add a custom control in python to add it to a list and saving it as part of your cached settings

**Comment by lincoln-lm** [comment]
With just a comma-separated input it would not support having different settings for each webhook. The likely implementation at this point is a normal dropdown that fills in/saves from the inputs on the GUI, with a checkbox to mark whether or not the webhook is enabled.
