### ISSUE TITLE
App crashes/errors when loading save file

### ISSUE THREAD

**Issue by realquantumsource** [Lincoln-LM/sv-live-map#59]
App fails to load save file mentioning can't find 1 star raid bin
images and sav [attached[](url)](url)
![Screenshot 2022-12-30 214915](https://user-images.githubusercontent.com/20935116/210153550-672b6f9e-cfbf-4085-bbdc-e170fb4729c9.png)
![Screenshot 2022-12-30 215031](https://user-images.githubusercontent.com/20935116/210153551-6d8e43aa-c91e-49b4-94bd-279a4eca603a.png)
[main.zip](https://github.com/Lincoln-LM/sv-live-map/files/10327876/main.zip)

**Comment by lincoln-lm** [comment]
Raid tables are required to load from save. Tables can either be obtained by connecting to a switch at least once, or by following https://github.com/Lincoln-LM/sv-live-map/issues/34#issuecomment-1365630036

**Comment by lincoln-lm** [comment]
If you have further questions I can answer them, but I'm closing this as it's not an issue.
